// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: careerhub/userinfo_service/restapi/restapi_grpc/restapi.proto

package restapi_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestApiGrpcClient is the client API for RestApiGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestApiGrpcClient interface {
	FindMatchJob(ctx context.Context, in *FindMatchJobRequest, opts ...grpc.CallOption) (*FindMatchJobResponse, error)
	AddCondition(ctx context.Context, in *AddConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error)
	UpdateCondition(ctx context.Context, in *UpdateConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error)
	DeleteCondition(ctx context.Context, in *DeleteConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error)
	UpdateAgreeToMail(ctx context.Context, in *UpdateAgreeToMailRequest, opts ...grpc.CallOption) (*IsSuccess, error)
}

type restApiGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRestApiGrpcClient(cc grpc.ClientConnInterface) RestApiGrpcClient {
	return &restApiGrpcClient{cc}
}

func (c *restApiGrpcClient) FindMatchJob(ctx context.Context, in *FindMatchJobRequest, opts ...grpc.CallOption) (*FindMatchJobResponse, error) {
	out := new(FindMatchJobResponse)
	err := c.cc.Invoke(ctx, "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/FindMatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restApiGrpcClient) AddCondition(ctx context.Context, in *AddConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error) {
	out := new(IsSuccess)
	err := c.cc.Invoke(ctx, "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/AddCondition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restApiGrpcClient) UpdateCondition(ctx context.Context, in *UpdateConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error) {
	out := new(IsSuccess)
	err := c.cc.Invoke(ctx, "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/UpdateCondition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restApiGrpcClient) DeleteCondition(ctx context.Context, in *DeleteConditionRequest, opts ...grpc.CallOption) (*IsSuccess, error) {
	out := new(IsSuccess)
	err := c.cc.Invoke(ctx, "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/DeleteCondition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restApiGrpcClient) UpdateAgreeToMail(ctx context.Context, in *UpdateAgreeToMailRequest, opts ...grpc.CallOption) (*IsSuccess, error) {
	out := new(IsSuccess)
	err := c.cc.Invoke(ctx, "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/UpdateAgreeToMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestApiGrpcServer is the server API for RestApiGrpc service.
// All implementations must embed UnimplementedRestApiGrpcServer
// for forward compatibility
type RestApiGrpcServer interface {
	FindMatchJob(context.Context, *FindMatchJobRequest) (*FindMatchJobResponse, error)
	AddCondition(context.Context, *AddConditionRequest) (*IsSuccess, error)
	UpdateCondition(context.Context, *UpdateConditionRequest) (*IsSuccess, error)
	DeleteCondition(context.Context, *DeleteConditionRequest) (*IsSuccess, error)
	UpdateAgreeToMail(context.Context, *UpdateAgreeToMailRequest) (*IsSuccess, error)
	mustEmbedUnimplementedRestApiGrpcServer()
}

// UnimplementedRestApiGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedRestApiGrpcServer struct {
}

func (UnimplementedRestApiGrpcServer) FindMatchJob(context.Context, *FindMatchJobRequest) (*FindMatchJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMatchJob not implemented")
}
func (UnimplementedRestApiGrpcServer) AddCondition(context.Context, *AddConditionRequest) (*IsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCondition not implemented")
}
func (UnimplementedRestApiGrpcServer) UpdateCondition(context.Context, *UpdateConditionRequest) (*IsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCondition not implemented")
}
func (UnimplementedRestApiGrpcServer) DeleteCondition(context.Context, *DeleteConditionRequest) (*IsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCondition not implemented")
}
func (UnimplementedRestApiGrpcServer) UpdateAgreeToMail(context.Context, *UpdateAgreeToMailRequest) (*IsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgreeToMail not implemented")
}
func (UnimplementedRestApiGrpcServer) mustEmbedUnimplementedRestApiGrpcServer() {}

// UnsafeRestApiGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestApiGrpcServer will
// result in compilation errors.
type UnsafeRestApiGrpcServer interface {
	mustEmbedUnimplementedRestApiGrpcServer()
}

func RegisterRestApiGrpcServer(s grpc.ServiceRegistrar, srv RestApiGrpcServer) {
	s.RegisterService(&RestApiGrpc_ServiceDesc, srv)
}

func _RestApiGrpc_FindMatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestApiGrpcServer).FindMatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/FindMatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestApiGrpcServer).FindMatchJob(ctx, req.(*FindMatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApiGrpc_AddCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestApiGrpcServer).AddCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/AddCondition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestApiGrpcServer).AddCondition(ctx, req.(*AddConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApiGrpc_UpdateCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestApiGrpcServer).UpdateCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/UpdateCondition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestApiGrpcServer).UpdateCondition(ctx, req.(*UpdateConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApiGrpc_DeleteCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestApiGrpcServer).DeleteCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/DeleteCondition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestApiGrpcServer).DeleteCondition(ctx, req.(*DeleteConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApiGrpc_UpdateAgreeToMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgreeToMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestApiGrpcServer).UpdateAgreeToMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.userinfo_service.restapi_grpc.RestApiGrpc/UpdateAgreeToMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestApiGrpcServer).UpdateAgreeToMail(ctx, req.(*UpdateAgreeToMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestApiGrpc_ServiceDesc is the grpc.ServiceDesc for RestApiGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestApiGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "careerhub.userinfo_service.restapi_grpc.RestApiGrpc",
	HandlerType: (*RestApiGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMatchJob",
			Handler:    _RestApiGrpc_FindMatchJob_Handler,
		},
		{
			MethodName: "AddCondition",
			Handler:    _RestApiGrpc_AddCondition_Handler,
		},
		{
			MethodName: "UpdateCondition",
			Handler:    _RestApiGrpc_UpdateCondition_Handler,
		},
		{
			MethodName: "DeleteCondition",
			Handler:    _RestApiGrpc_DeleteCondition_Handler,
		},
		{
			MethodName: "UpdateAgreeToMail",
			Handler:    _RestApiGrpc_UpdateAgreeToMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "careerhub/userinfo_service/restapi/restapi_grpc/restapi.proto",
}
