// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: careerhub/userinfo_service/restapi/restapi_grpc/scrapJob.proto

package restapi_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScrapJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetScrapJobsRequest) Reset() {
	*x = GetScrapJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapJobsRequest) ProtoMessage() {}

func (x *GetScrapJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapJobsRequest.ProtoReflect.Descriptor instead.
func (*GetScrapJobsRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{0}
}

func (x *GetScrapJobsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetScrapJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScrapJobs []*ScrapJob `protobuf:"bytes,1,rep,name=scrapJobs,proto3" json:"scrapJobs,omitempty"`
}

func (x *GetScrapJobsResponse) Reset() {
	*x = GetScrapJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapJobsResponse) ProtoMessage() {}

func (x *GetScrapJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapJobsResponse.ProtoReflect.Descriptor instead.
func (*GetScrapJobsResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{1}
}

func (x *GetScrapJobsResponse) GetScrapJobs() []*ScrapJob {
	if x != nil {
		return x.ScrapJobs
	}
	return nil
}

type ScrapJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site   string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *ScrapJob) Reset() {
	*x = ScrapJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapJob) ProtoMessage() {}

func (x *ScrapJob) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapJob.ProtoReflect.Descriptor instead.
func (*ScrapJob) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapJob) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScrapJob) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type AddScrapJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
}

func (x *AddScrapJobRequest) Reset() {
	*x = AddScrapJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScrapJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScrapJobRequest) ProtoMessage() {}

func (x *AddScrapJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScrapJobRequest.ProtoReflect.Descriptor instead.
func (*AddScrapJobRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{3}
}

func (x *AddScrapJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddScrapJobRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AddScrapJobRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

type RemoveScrapJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
}

func (x *RemoveScrapJobRequest) Reset() {
	*x = RemoveScrapJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveScrapJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveScrapJobRequest) ProtoMessage() {}

func (x *RemoveScrapJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveScrapJobRequest.ProtoReflect.Descriptor instead.
func (*RemoveScrapJobRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveScrapJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveScrapJobRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RemoveScrapJobRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

var File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto protoreflect.FileDescriptor

var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x27, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x09, 0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x4a, 0x6f, 0x62, 0x52, 0x09, 0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x36,
	0x0a, 0x08, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x32, 0xed, 0x02, 0x0a, 0x0f, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x8b, 0x01,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x3c,
	0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x63,
	0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0b, 0x41,
	0x64, 0x64, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x3b, 0x2e, 0x63, 0x61, 0x72,
	0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x68, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f,
	0x62, 0x12, 0x3e, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x63, 0x61, 0x72,
	0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescOnce sync.Once
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData = file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc
)

func file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP() []byte {
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescOnce.Do(func() {
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData = protoimpl.X.CompressGZIP(file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData)
	})
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData
}

var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes = []interface{}{
	(*GetScrapJobsRequest)(nil),   // 0: careerhub.userinfo_service.restapi_grpc.GetScrapJobsRequest
	(*GetScrapJobsResponse)(nil),  // 1: careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse
	(*ScrapJob)(nil),              // 2: careerhub.userinfo_service.restapi_grpc.ScrapJob
	(*AddScrapJobRequest)(nil),    // 3: careerhub.userinfo_service.restapi_grpc.AddScrapJobRequest
	(*RemoveScrapJobRequest)(nil), // 4: careerhub.userinfo_service.restapi_grpc.RemoveScrapJobRequest
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs = []int32{
	2, // 0: careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse.scrapJobs:type_name -> careerhub.userinfo_service.restapi_grpc.ScrapJob
	0, // 1: careerhub.userinfo_service.restapi_grpc.ScrapJobService.GetScrapJobs:input_type -> careerhub.userinfo_service.restapi_grpc.GetScrapJobsRequest
	3, // 2: careerhub.userinfo_service.restapi_grpc.ScrapJobService.AddScrapJob:input_type -> careerhub.userinfo_service.restapi_grpc.AddScrapJobRequest
	4, // 3: careerhub.userinfo_service.restapi_grpc.ScrapJobService.RemoveScrapJob:input_type -> careerhub.userinfo_service.restapi_grpc.RemoveScrapJobRequest
	1, // 4: careerhub.userinfo_service.restapi_grpc.ScrapJobService.GetScrapJobs:output_type -> careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse
	5, // 5: careerhub.userinfo_service.restapi_grpc.ScrapJobService.AddScrapJob:output_type -> google.protobuf.Empty
	5, // 6: careerhub.userinfo_service.restapi_grpc.ScrapJobService.RemoveScrapJob:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_init() }
func file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_init() {
	if File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScrapJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveScrapJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes,
		DependencyIndexes: file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs,
		MessageInfos:      file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes,
	}.Build()
	File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto = out.File
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc = nil
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes = nil
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs = nil
}
