// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: careerhub/userinfo_service/restapi/restapi_grpc/scrapJob.proto

package restapi_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScrapJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Tag    *string `protobuf:"bytes,2,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
}

func (x *GetScrapJobsRequest) Reset() {
	*x = GetScrapJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapJobsRequest) ProtoMessage() {}

func (x *GetScrapJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapJobsRequest.ProtoReflect.Descriptor instead.
func (*GetScrapJobsRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{0}
}

func (x *GetScrapJobsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetScrapJobsRequest) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

type GetScrapJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScrapJobs []*ScrapJob `protobuf:"bytes,1,rep,name=scrapJobs,proto3" json:"scrapJobs,omitempty"`
}

func (x *GetScrapJobsResponse) Reset() {
	*x = GetScrapJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapJobsResponse) ProtoMessage() {}

func (x *GetScrapJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapJobsResponse.ProtoReflect.Descriptor instead.
func (*GetScrapJobsResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{1}
}

func (x *GetScrapJobsResponse) GetScrapJobs() []*ScrapJob {
	if x != nil {
		return x.ScrapJobs
	}
	return nil
}

type ScrapJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site      string   `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string   `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
	Tags      []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ScrapJob) Reset() {
	*x = ScrapJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapJob) ProtoMessage() {}

func (x *ScrapJob) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapJob.ProtoReflect.Descriptor instead.
func (*ScrapJob) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapJob) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ScrapJob) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

func (x *ScrapJob) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddScrapJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
}

func (x *AddScrapJobRequest) Reset() {
	*x = AddScrapJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScrapJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScrapJobRequest) ProtoMessage() {}

func (x *AddScrapJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScrapJobRequest.ProtoReflect.Descriptor instead.
func (*AddScrapJobRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{3}
}

func (x *AddScrapJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddScrapJobRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AddScrapJobRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

type RemoveScrapJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
}

func (x *RemoveScrapJobRequest) Reset() {
	*x = RemoveScrapJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveScrapJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveScrapJobRequest) ProtoMessage() {}

func (x *RemoveScrapJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveScrapJobRequest.ProtoReflect.Descriptor instead.
func (*RemoveScrapJobRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveScrapJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveScrapJobRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RemoveScrapJobRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

type AddTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
	Tag       string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *AddTagRequest) Reset() {
	*x = AddTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagRequest) ProtoMessage() {}

func (x *AddTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagRequest.ProtoReflect.Descriptor instead.
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{5}
}

func (x *AddTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTagRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AddTagRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

func (x *AddTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemoveTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Site      string `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	PostingId string `protobuf:"bytes,3,opt,name=postingId,proto3" json:"postingId,omitempty"`
	Tag       string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *RemoveTagRequest) Reset() {
	*x = RemoveTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagRequest) ProtoMessage() {}

func (x *RemoveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveTagRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RemoveTagRequest) GetPostingId() string {
	if x != nil {
		return x.PostingId
	}
	return ""
}

func (x *RemoveTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetScrapTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetScrapTagsRequest) Reset() {
	*x = GetScrapTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapTagsRequest) ProtoMessage() {}

func (x *GetScrapTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapTagsRequest.ProtoReflect.Descriptor instead.
func (*GetScrapTagsRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{7}
}

func (x *GetScrapTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetScrapTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *GetScrapTagsResponse) Reset() {
	*x = GetScrapTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScrapTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapTagsResponse) ProtoMessage() {}

func (x *GetScrapTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapTagsResponse.ProtoReflect.Descriptor instead.
func (*GetScrapTagsResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{8}
}

func (x *GetScrapTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type IsExistedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExisted bool `protobuf:"varint,1,opt,name=isExisted,proto3" json:"isExisted,omitempty"`
}

func (x *IsExistedResponse) Reset() {
	*x = IsExistedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsExistedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExistedResponse) ProtoMessage() {}

func (x *IsExistedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExistedResponse.ProtoReflect.Descriptor instead.
func (*IsExistedResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP(), []int{9}
}

func (x *IsExistedResponse) GetIsExisted() bool {
	if x != nil {
		return x.IsExisted
	}
	return false
}

var File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto protoreflect.FileDescriptor

var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x27, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x74, 0x61, 0x67, 0x22, 0x67, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x09,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a,
	0x6f, 0x62, 0x52, 0x09, 0x73, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x50, 0x0a,
	0x08, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22,
	0x5e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22,
	0x61, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x22, 0x6b, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x6e, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x31, 0x0a, 0x11, 0x49, 0x73,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x32, 0xa0, 0x06,
	0x0a, 0x0c, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x47, 0x72, 0x70, 0x63, 0x12, 0x8b,
	0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x12,
	0x3c, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e,
	0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x3b, 0x2e, 0x63, 0x61,
	0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x8c, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x4a, 0x6f, 0x62, 0x12, 0x3e, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x73,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x7c, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x12, 0x36, 0x2e, 0x63, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x73, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x82, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x12, 0x39, 0x2e, 0x63, 0x61,
	0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68,
	0x75, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x8b, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x54,
	0x61, 0x67, 0x73, 0x12, 0x3c, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3d, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x29, 0x5a, 0x27, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescOnce sync.Once
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData = file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc
)

func file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescGZIP() []byte {
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescOnce.Do(func() {
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData = protoimpl.X.CompressGZIP(file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData)
	})
	return file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDescData
}

var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes = []interface{}{
	(*GetScrapJobsRequest)(nil),   // 0: careerhub.userinfo_service.restapi_grpc.GetScrapJobsRequest
	(*GetScrapJobsResponse)(nil),  // 1: careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse
	(*ScrapJob)(nil),              // 2: careerhub.userinfo_service.restapi_grpc.ScrapJob
	(*AddScrapJobRequest)(nil),    // 3: careerhub.userinfo_service.restapi_grpc.AddScrapJobRequest
	(*RemoveScrapJobRequest)(nil), // 4: careerhub.userinfo_service.restapi_grpc.RemoveScrapJobRequest
	(*AddTagRequest)(nil),         // 5: careerhub.userinfo_service.restapi_grpc.AddTagRequest
	(*RemoveTagRequest)(nil),      // 6: careerhub.userinfo_service.restapi_grpc.RemoveTagRequest
	(*GetScrapTagsRequest)(nil),   // 7: careerhub.userinfo_service.restapi_grpc.GetScrapTagsRequest
	(*GetScrapTagsResponse)(nil),  // 8: careerhub.userinfo_service.restapi_grpc.GetScrapTagsResponse
	(*IsExistedResponse)(nil),     // 9: careerhub.userinfo_service.restapi_grpc.IsExistedResponse
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs = []int32{
	2,  // 0: careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse.scrapJobs:type_name -> careerhub.userinfo_service.restapi_grpc.ScrapJob
	0,  // 1: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.GetScrapJobs:input_type -> careerhub.userinfo_service.restapi_grpc.GetScrapJobsRequest
	3,  // 2: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.AddScrapJob:input_type -> careerhub.userinfo_service.restapi_grpc.AddScrapJobRequest
	4,  // 3: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.RemoveScrapJob:input_type -> careerhub.userinfo_service.restapi_grpc.RemoveScrapJobRequest
	5,  // 4: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.AddTag:input_type -> careerhub.userinfo_service.restapi_grpc.AddTagRequest
	6,  // 5: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.RemoveTag:input_type -> careerhub.userinfo_service.restapi_grpc.RemoveTagRequest
	7,  // 6: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.GetScrapTags:input_type -> careerhub.userinfo_service.restapi_grpc.GetScrapTagsRequest
	1,  // 7: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.GetScrapJobs:output_type -> careerhub.userinfo_service.restapi_grpc.GetScrapJobsResponse
	10, // 8: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.AddScrapJob:output_type -> google.protobuf.Empty
	9,  // 9: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.RemoveScrapJob:output_type -> careerhub.userinfo_service.restapi_grpc.IsExistedResponse
	9,  // 10: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.AddTag:output_type -> careerhub.userinfo_service.restapi_grpc.IsExistedResponse
	9,  // 11: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.RemoveTag:output_type -> careerhub.userinfo_service.restapi_grpc.IsExistedResponse
	8,  // 12: careerhub.userinfo_service.restapi_grpc.ScrapJobGrpc.GetScrapTags:output_type -> careerhub.userinfo_service.restapi_grpc.GetScrapTagsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_init() }
func file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_init() {
	if File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScrapJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveScrapJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScrapTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsExistedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes,
		DependencyIndexes: file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs,
		MessageInfos:      file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_msgTypes,
	}.Build()
	File_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto = out.File
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_rawDesc = nil
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_goTypes = nil
	file_careerhub_userinfo_service_restapi_restapi_grpc_scrapJob_proto_depIdxs = nil
}
